#!/usr/bin/perl

use strict;
use warnings;


# Init Json
use JSON::XS;
my $coder = JSON::XS->new->pretty;


# Warn levels
my $warnLevel   = 12;
my $critLevel   = 50;

my $return = {
    Name       => "CountConnectedUsers",
    Version    => "0.01",
    
    Status     => 398,
    Message    => "No results",

    Value      => "",
    Detail     => "",
};


# Exec
my $fnret = `who`;
chomp($fnret);

my $uptime = `uptime`;
chomp($uptime);


my @users = split("\n",$fnret);

if($? != 0)
{
    $return->{'Status'}     = 500;
    $return->{'Message'}    = $fnret . " - " . $!;
}
else
{
    my $userCount = scalar(@users);

    $return->{'Value'}      = $userCount;
    $return->{'Message'}    = $uptime;
    $return->{'Status'}    = 100;

    if($userCount >= $warnLevel)
    {
        $return->{'Status'} = 250;
    }
    if($userCount >= $critLevel)
    {
        $return->{'Status'} = 350;
    }

    
}


print $coder->encode( $return );
